version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nx:
        patterns: ['@nx/*', 'nx']
      angular:
        patterns: ['@angular/*', 'angular-eslint']
      nest:
        patterns: ['@nestjs/*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
